# -*- coding: utf-8 -*-
"""rag_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfyeDMmDUkk3ubKHXxREVqXbGWmfqWwI

# 🔍 RAG Pipeline — Retrieval-Augmented Generation

A complete end-to-end RAG system with:
- **Document Loading** from `.txt` files
- **Chunking** with overlap
- **Embeddings** via SentenceTransformers + FAISS
- **LLM Generation** via HuggingFace (TinyLlama)
- **Gradio UI** with sliders for TOP_K and MIN_SCORE

> Run cells **top-to-bottom**. Upload your `.txt` files when prompted in Cell 3.
"""

# Cell 1 — Install packages
!pip install -q faiss-cpu sentence-transformers transformers accelerate gradio torch
print("✅ All packages installed.")

# Cell 2 — Imports
import os, textwrap
from pathlib import Path
from typing import List, Dict, Tuple
import numpy as np
import faiss
import torch
import gradio as gr
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline as hf_pipeline

print("✅ Imports OK")
print(f"   PyTorch : {torch.__version__}")
print(f"   CUDA    : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"   GPU     : {torch.cuda.get_device_name(0)}")

# Cell 3 — Upload .txt knowledge-base files
from google.colab import files as colab_files

DATA_DIR = "/content/data"
os.makedirs(DATA_DIR, exist_ok=True)

print("📂 Please upload your .txt knowledge-base files:")
uploaded = colab_files.upload()

for filename, content in uploaded.items():
    dest = os.path.join(DATA_DIR, filename)
    with open(dest, 'wb') as f:
        f.write(content)
    print(f"   ✅ Saved: {filename}  ({len(content):,} bytes)")

txt_files = list(Path(DATA_DIR).glob('*.txt'))
print(f"\n📄 Total .txt files ready: {len(txt_files)}")
for p in txt_files:
    print(f"   • {p.name}")

# Cell 4 — Document Loading

def load_documents(data_dir: str) -> List[Dict]:
    """Load all .txt files. Returns List[{filename, text}]."""
    documents = []
    for path in sorted(Path(data_dir).glob('*.txt')):
        text = path.read_text(encoding='utf-8').strip()
        if text:
            documents.append({'filename': path.name, 'text': text})
            print(f"   [loaded] {path.name}  —  {len(text):,} chars")
    print(f"\n✅ Loaded {len(documents)} document(s)")
    return documents

documents = load_documents(DATA_DIR)

# Cell 5 — Chunking
# Overlapping character-level chunks. Each chunk: {chunk_id, filename, text}

CHUNK_SIZE = 400
OVERLAP    = 80

def chunk_document(doc: Dict, chunk_size: int = CHUNK_SIZE, overlap: int = OVERLAP) -> List[Dict]:
    text, filename = doc['text'], doc['filename']
    chunks, start, chunk_id = [], 0, 0
    while start < len(text):
        piece = text[start : start + chunk_size].strip()
        if piece:
            chunks.append({'chunk_id': chunk_id, 'filename': filename, 'text': piece})
            chunk_id += 1
        start += chunk_size - overlap
    return chunks

def chunk_all_documents(docs: List[Dict]) -> List[Dict]:
    all_chunks = []
    for doc in docs:
        chunks = chunk_document(doc)
        all_chunks.extend(chunks)
        print(f"   [chunked] {doc['filename']}  ->  {len(chunks)} chunks")
    print(f"\n✅ Total chunks: {len(all_chunks)}  (size={CHUNK_SIZE}, overlap={OVERLAP})")
    return all_chunks

all_chunks = chunk_all_documents(documents)

print("\n── First 3 chunks ──────────────────────────────────")
for c in all_chunks[:3]:
    print(f"  [{c['chunk_id']}] {c['filename']}")
    preview = c['text'][:100].replace('\n', ' ')
    print(f"      {repr(preview)}")
    print()

# Cell 6 — Embeddings + FAISS index  (model loaded ONCE)
# all-MiniLM-L6-v2: 22M params, 384-dim, fast and accurate.
# IndexFlatIP on L2-normalised vectors = cosine similarity.

EMBED_MODEL_NAME = "all-MiniLM-L6-v2"

print(f"Loading embedding model: {EMBED_MODEL_NAME} ...")
embed_model = SentenceTransformer(EMBED_MODEL_NAME)
print(f"✅ Embedding model ready  (dim={embed_model.get_sentence_embedding_dimension()})")

def build_faiss_index(chunks: List[Dict], model: SentenceTransformer):
    texts = [c['text'] for c in chunks]
    print(f"   Embedding {len(texts)} chunks ...")
    embeddings = model.encode(
        texts,
        batch_size=64,
        show_progress_bar=True,
        normalize_embeddings=True,
        convert_to_numpy=True,
    ).astype('float32')
    dim   = embeddings.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(embeddings)
    print(f"✅ FAISS index built  ({index.ntotal} vectors, dim={dim})")
    return index, embeddings

faiss_index, chunk_embeddings = build_faiss_index(all_chunks, embed_model)

# Cell 7 — Retrieval
# Embed the query, search FAISS, filter by min_score.

def retrieve(query: str, top_k: int = 3, min_score: float = 0.4) -> List[Dict]:
    q_vec = embed_model.encode(
        [query], normalize_embeddings=True, convert_to_numpy=True
    ).astype('float32')
    scores, indices = faiss_index.search(q_vec, top_k)
    hits = []
    for score, idx in zip(scores[0], indices[0]):
        if idx < 0 or float(score) < min_score:
            continue
        c = all_chunks[idx]
        hits.append({
            'filename': c['filename'],
            'chunk_id': c['chunk_id'],
            'text':     c['text'],
            'score':    round(float(score), 4),
        })
    return hits

# Smoke test
test_hits = retrieve("What did John McCarthy do in 1956?", top_k=3, min_score=0.3)
print(f"Smoke test: {len(test_hits)} hit(s)")
for h in test_hits:
    print(f"  [{h['chunk_id']}] {h['filename']}  score={h['score']}")
    print(f"      {repr(h['text'][:100])}")
    print()

# Cell 8 — LLM loading  (loaded ONCE, reused every query)
# TinyLlama-1.1B-Chat: 1.1B params, fits on Colab free T4 GPU.

LLM_MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

print(f"Loading LLM: {LLM_MODEL_NAME}")
print("   (first run downloads ~2 GB — takes 1-2 min) ...")

llm_tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL_NAME)
llm_model     = AutoModelForCausalLM.from_pretrained(
    LLM_MODEL_NAME,
    torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map  = "auto",
)
llm_pipeline = hf_pipeline(
    "text-generation",
    model            = llm_model,
    tokenizer        = llm_tokenizer,
    max_new_tokens   = 256,
    do_sample        = False,
    return_full_text = False,
    eos_token_id     = llm_tokenizer.eos_token_id,
)
print(f"\n✅ LLM ready: {LLM_MODEL_NAME}")

# Cell 9 — Prompt building and answer generation

MAX_CONTEXT_CHARS = 2000

def build_context(hits: List[Dict]) -> str:
    parts, total = [], 0
    for i, hit in enumerate(hits):
        text = hit['text'].strip()
        if total + len(text) > MAX_CONTEXT_CHARS:
            break
        parts.append(f"[{i+1}] (source: {hit['filename']})\n{text}")
        total += len(text)
    return '\n\n'.join(parts)

def generate_answer(query: str, hits: List[Dict]) -> str:
    context = build_context(hits)
    system_msg = (
        "You are a helpful assistant. "
        "Answer the question using ONLY the context below. "
        "If the answer is not in the context, say: "
        "'I don't know based on the provided documents.'\n\n"
        f"Context:\n{context}"
    )
    messages = [
        {'role': 'system', 'content': system_msg},
        {'role': 'user',   'content': query},
    ]
    prompt = llm_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    output = llm_pipeline(prompt)
    return output[0]['generated_text'].strip()

# Smoke test
if test_hits:
    print("Answer:", generate_answer("What did John McCarthy do in 1956?", test_hits))
else:
    print("No hits from smoke test — skipping.")

# Cell 10 — Full RAG query function (entry point for Gradio)

NO_SOURCES_WARNING = (
    "⚠️ No relevant sources found.\n\n"
    "Try lowering MIN_SCORE or increasing TOP_K."
)

def format_sources(hits: List[Dict]) -> str:
    if not hits:
        return 'No sources.'
    lines = []
    for i, hit in enumerate(hits, 1):
        bar_len = int(hit['score'] * 20)
        bar     = '█' * bar_len + '░' * (20 - bar_len)
        preview = textwrap.shorten(hit['text'], width=200, placeholder=' [...]')
        lines.append(
            f"{'─'*60}\n"
            f"  #{i}  {hit['filename']}   chunk {hit['chunk_id']}\n"
            f"  Score : {hit['score']:.4f}  |{bar}|\n"
            f"  Text  : {preview}\n"
        )
    return '\n'.join(lines)

def rag_query(question: str, top_k: int, min_score: float) -> Tuple[str, str]:
    question = question.strip()
    if not question:
        return "Please enter a question.", ""
    hits = retrieve(question, top_k=int(top_k), min_score=float(min_score))
    if not hits:
        return NO_SOURCES_WARNING, 'No sources passed the similarity threshold.'
    answer  = generate_answer(question, hits)
    sources = format_sources(hits)
    return answer, sources

# Quick test
ans, src = rag_query("What is the greenhouse effect?", top_k=3, min_score=0.3)
print("Answer:", ans[:300])
print("\nSources:\n", src[:400])

# Cell 11 — Gradio UI

n_docs   = len(documents)
n_chunks = len(all_chunks)

with gr.Blocks(title='RAG Pipeline', theme=gr.themes.Soft()) as demo:

    gr.Markdown('# 🔍 RAG Pipeline — Ask Your Documents')
    gr.Markdown(
        f'Knowledge base: **{n_docs} doc(s)**, **{n_chunks} chunks** | '
        f'Embed: `{EMBED_MODEL_NAME}` | LLM: `{LLM_MODEL_NAME}`'
    )

    with gr.Row():
        question_box = gr.Textbox(
            label='Your question',
            placeholder='e.g. What did John McCarthy do in 1956?',
            lines=2, scale=4,
        )

    with gr.Row():
        top_k_slider = gr.Slider(
            minimum=1, maximum=10, value=3, step=1,
            label='TOP_K — number of chunks to retrieve',
        )
        min_score_slider = gr.Slider(
            minimum=0.0, maximum=1.0, value=0.4, step=0.05,
            label='MIN_SCORE — minimum similarity threshold',
        )

    submit_btn  = gr.Button('Ask', variant='primary')
    answer_box  = gr.Textbox(label='Answer',       lines=6,  interactive=False)
    sources_box = gr.Textbox(label='Sources Used', lines=12, interactive=False)

    gr.Examples(
        examples=[
            ['What did John McCarthy do in 1956?',            3, 0.4],
            ['How does the greenhouse effect work?',           3, 0.4],
            ['What is the surface code in quantum computing?', 3, 0.35],
            ['When was the first human in space?',             3, 0.4],
            ['What is the transformer architecture?',          5, 0.3],
        ],
        inputs=[question_box, top_k_slider, min_score_slider],
    )

    submit_btn.click(
        fn=rag_query,
        inputs=[question_box, top_k_slider, min_score_slider],
        outputs=[answer_box, sources_box],
    )
    question_box.submit(
        fn=rag_query,
        inputs=[question_box, top_k_slider, min_score_slider],
        outputs=[answer_box, sources_box],
    )

demo.launch(share=True, debug=False)

